version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: demo_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - debezium-net
    volumes:
      - zookeeper-data:/var/lib/zookeeper
    labels:
      - "project=debeziumdemo"
      - "tier=infra"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: demo_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - debezium-net
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/var/lib/kafka/data
    labels:
      - "project=debeziumdemo"
      - "tier=infra"

  mysql:
    image: mysql:8.0.34
    container_name: demo_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - debezium-net
    command: >
      --server-id=85744
      --log-bin=mysql-bin
      --binlog-format=ROW
      --binlog-row-image=FULL
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    labels:
      - "project=debeziumdemo"
      - "tier=db"

  connect:
    image: debezium/connect:2.5
    container_name: demo_connect
    ports:
      - "8183:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: product-cdc-connect
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-statuses
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECTOR_PLUGIN_PATH: /kafka/connect
      DATABASE_HISTORY_KAFKA_TOPIC: dbhistory.demo
    networks:
      - debezium-net
    depends_on:
      - kafka
      - mysql
    labels:
      - "project=debeziumdemo"
      - "tier=infra"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: demo_kafka_ui
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      - debezium-net
    labels:
      - "project=debeziumdemo"
      - "tier=infra"

volumes:
  kafka-data:
  zookeeper-data:
  mysql-data:

networks:
  debezium-net:
    driver: bridge
