server:
  port: 8081

spring:
  application:
    name: debenziumdemo

  datasource:
    url: jdbc:mysql://localhost:3307/db_order
    username: root
    password: root

  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

debezium:
  connector:
    name: order-connector
    topic-prefix: db_order
    connector-class: io.debezium.connector.mysql.MySqlConnector
    class: io.debezium.connector.mysql.MySqlConnector
    endpoint-url: http://localhost:8183/connectors
    database:
      hostname: mysql
      port: 3306
      user: root
      password: root
      server-id: 85744
      server-name: dbserver_order
      include-list: db_order
    table:
      include-list: db_order.outbox_event
    kafka:
      bootstrap-servers: kafka:29092
    config-topics:
      config-storage-topic: connect-configs
      offset-storage-topic: connect-offsets
      status-storage-topic: connect-statuses
    tombstones-on-delete: false
    include-schema-changes: false
    schema-history:
      bootstrap-servers: kafka:29092
      topic: dbhistory.order

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG